### ISSUE TITLE
Error loading page with error code -1101 on IOS

### ISSUE THREAD

**Issue by vandiepbui** [react-native-community/react-native-webview#1004]
Hi,
I'm facing a problem when upload app to apple store. My app was rejected with webview error. 
**Domain: NSURLErrorDomain**
**Error Code:  -1101**
**Description: File is a directory**

My app uses webview to load a http url. It work when I test on simulator without any warning or error, but when I upload to apple store. It does not work.

Note: Android app version work perfectly and it was uploaded to CH play successful. Just error on iOS when upload to apple store.
Please help me!

**Comment by i-bar** [comment]
Still encounter this... :(

**Comment by bambismurfen** [comment]
Might be a coincidence but I had a very similar issue on IOS (only) with this error status. The issue seemed to be that I initialised my WebView with an empty URL. The reason for this was that I was fetching the URL through an API call in ComponentDidMount().

So my solution in render() was simply like this: 

{this.state.authUrl !== '' && (
					<WebView
						source={{uri: this.state.authUrl}}
             ....
/> 
)}

Haven't been able to reproduce it ever since. However, it only occurred when stressing the system, so basically depending on response time from our servers.
