### ISSUE TITLE
Podfile React dependency?

### ISSUE THREAD

**Issue by garrettm** [react-native-community/react-native-webview#102]
When I install this using cocoapods, I see:
`Using React (0.11.0)`

This is an old version of React, and the Cocoapod is deprecated https://cocoapods.org/pods/React
The old version appears to cause native build errors (types and function signatures/names have changed).

Should React be removed as a dependency in the `.podspec`?

**Comment by Titozzz** [comment]
It should not be removed, you cannot use cocoapods only for some dependecies and build react the way you used to. When you build react-native using cocoapods, you redirect it to your node_modules so that it takes the correct version. I'll write an article about that since many people are confused !

In the meantime please
 remove the line containing react-native-webview from your profile.
 Rename your podfile to podfile.tmp
 Run react-native link react-native-webview
(It should link it the old way and not inside your profile )
Rename your profile back to normal
Run pod install

Enjoy :tada:

**Comment by garrettm** [comment]
This worked, thanks!
