### ISSUE TITLE
requestFocus() call crashes on iOS

### ISSUE THREAD

**Issue by alexisbronchart** [react-native-community/react-native-webview#1021]
**Bug description:**
When I call requestFocus() on a webview I'm getting this error:
`dispatchViewManagerCommand must be called with a string or integer command`
This happens only on iOS, android looks OK.

**To Reproduce:**
Pull the repro I made here: https://github.com/alexisbronchart/WebViewFocus

**Expected behavior:**
The app should load the webview with the text input already focused as it does on android.

**Environment:**
 - OS: iOS
 - OS version: 13
 - react-native version: 0.61.4
 - react-native-webview version: 7.5.1

**Comment by 54sword** [comment]
i have the same problem.

**Comment by jqn** [comment]
Subscribing

**Comment by gs-rranjan** [comment]
Having the issue, when trying to focus a webView in IOS. Any solution for this ?

**Comment by seanstrom** [comment]
If anyone is running into this issue, you should be able to set the [`keyboardDisplayRequiresUserAction`](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#keyboardDisplayRequiresUserAction) prop to `false` (for IOS) and then request focus by using the [`injectedJavaScript`](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#injectedjavascript) prop.

**Pseudo Code Example**
```javascript
const INJECTED_JAVASCRIPT = `(function() {
    var inputId = 'search_input_react';
    var searchInputElement = window.document.getElementById(inputId);

    if (searchInputElement) {
      searchInputElement.focus();
    }
})();`;

<WebView
  source={{ uri: 'https://reactnative.dev' }}
  injectedJavaScript={INJECTED_JAVASCRIPT}
  keyboardDisplayRequiresUserAction={false}
/>;
```

**Comment by dimitarnestorov** [comment]
Issue is still here. @seanstrom thanks for the workaround.

**Comment by Slapbox** [comment]
Issue persists for me with the exact same error message, `dispatchViewManagerCommand must be called with a string or integer command`

- `react-native-webview@10.7.0`
- `expo@39.0.3`

**Comment by Slapbox** [comment]
I absolutely cannot find a workaround here. Does anyone have any tips?

In our case, we're trying to focus the a DOM node using `this.webview.current.injectJavaScript([ourcommand])` instead of `injectedJavaScript` prop, but the injected code is essentially the same, and we get the same error as OP.

@dimitarnestorov, I assume you mean you had to `blur` a DOM element inside the webview, right? Because as far as I can tell the webview itself doesn't have a `blur` method. Were you getting an error  without blurring, or just a lack of focus?

**Comment by Slapbox** [comment]
Anybody get this working? Still a no for us, even with `11.2.3`. We still get an identical error. Can anyone provide any insight on this?

**Comment by seanstrom** [comment]
@Slapbox It's been a while since I've dug into this, though I can try to help 😃.
I'm not sure what the best way to compare notes will be, but I think I can post a demo with `react-native-webview` and `expo`. Are there any other dependencies that you're using in your code? Can you provide a small example of how you're using the ref version of the API? I'm not as familiar with the ref API in this case.

Based on my experience of using `react-native-webview`, I can confirm that calling `.focus` on an element through the `injectedJavaScript` prop was a "good-enough" workaround. Though, there's a chance that loading the initial HTML or content of the webview isn't "ready" before the `.focus` call on the node. In my case, I was loading the HTML and waiting for the page to fully load before calling `.focus`, I may even have deferred the call with a `setTimeout` too.

Some ideas for debugging:
* Double check the injected code is running, maybe with a `console.log` statement
* Verify that the element is being focused, you can try to attach styles or event handlers on the element to detect focus
* Potentially play around with `setTimeout` around the `.focus` call, this can help with DOM elements that aren't ready
