### ISSUE TITLE
WebView doesn't have momentum scrolling - IOS

### ISSUE THREAD

**Issue by avnerI** [react-native-community/react-native-webview#1070]
The webView doesn't have momentum scrolling for IOS devices.
No matter if the destination URL has ` -webkit-overflow-scrolling: touch` css property set.

To Reproduce:
1. Any fresh installation of react-native
2. Install react-native-webview
3. Run on IOS device when the url is directing to a website that provides momentum scrolling in regular browser (Safari)

<img width="884" alt="Screen Shot 2019-12-09 at 16 46 22" src="https://user-images.githubusercontent.com/44140044/70445335-0b042080-1aa4-11ea-8fd9-9eb4f54b81ca.png">

Expecting to be able to scroll with momentum scrolling in IOS devices

Environment:
 - OS: IOS 
 - OS version: 11.0 and above 
 - react-native version: 0.61.5
 - react-native-webview version: 7.6.0

**Comment by avnerI** [comment]
I've found this:
https://github.com/facebook/react-native/pull/5527
just add `<WebView .....
                            decelerationRate='normal'
...
/>
`

The naming and the change in file names on the IOS side made it hard to find

**Comment by phyng** [comment]
@avnerI Thank you, you made my day!

**Comment by Rutvij07** [comment]
The solution worked , lovely

**Comment by Rajeshkanth** [comment]
Hi guys, im facing an issue which is the web view is rendered in ios app (flutter) the web view has heading, p tag, 4 inputs and a submit button which fixed in bottom of the page, when the input gets focus, the keyboard opens and after clicking on the second input the total page is coming down behind the keyboard, this issue is resolved if the 
<section> 
<form>
<h></h>
<p></p>
<div>
4 inputs with labels
</div>
</form>
</section>

now if the section is given as above 60rem for the height it is not coming behind the keyboard, and it is scrollable when keyboard presents, but there is a catch when cliking for the first time, the section is set to 60rem so it is more scrollable to end with white spaces, but i dont want that empty spaces at the end of the page, and the subsequent cliicks on the input makes the whitespaces gone (empty space ), i need help to rectify this.

**Comment by saeid-elio** [comment]
The solution suggested by @avnerI should be added to Webview's documentation.

**Comment by jslee-tpz** [comment]
> After upgrading my `react native` and `react-native-webview` to latest versions (0.78.0 and 13.13.2 respectively) the existing solution of `decelerationRate="normal"` started throwing following error on android phones:
> 
> ```
> Exception in HotFunction: Unable to convert string to floating point value: "normal"
> ```
> 
> So I had to use `decelerationRate={0.998}` instead.

It’s interesting that this issue is surfacing on Android, 
considering the 'normal' property should already be defaulted to ```0.998```.
