### ISSUE TITLE
incognito property does not respond to false or null

### ISSUE THREAD

**Issue by bobsmits** [react-native-community/react-native-webview#1143]
**Bug description:**
When setting the incognito property to false or null the webview acts as if incognito is true. At least cookies are not remembered. When setting incognito to undefined it works as expected. 

**To Reproduce:**
 ```
           <WebView
              source={{ uri: urlwithcookies }}
              sharedCookiesEnabled={true}
              incognito={false}
            />
```

**Expected behavior:**
When incognito is set to false or null it remembers my cookies. 

**Environment:**
 - OS: Tested on android
 - OS version: -
 - react-native version: 0.60.5
 - react-native-webview version: 8.0.3

**Comment by clamiax** [comment]
I think the issue is here:

https://github.com/react-native-community/react-native-webview/blob/344aab591a920159bbec30f97b42bbb12573824b/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L401

The `enabled` flag is only partially implemented while all cookies, cache and form data are cleared regardless on this flag. Hope this helps.

**Comment by pdandradeb** [comment]
I've created this PR https://github.com/react-native-community/react-native-webview/pull/1465 to fix this issue.
