### ISSUE TITLE
onLoadEnd is called twice on every click to new url in Android

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-webview#1148]
**Bug description:**
onLoadEnd is called twice in Android, whereas with same behavior in IOS, it is called only once. 
Upon looking at nativeEvent, first loadEnd seems to be called before the update of the 'title' of the new url, and the second call with the updated title. On IOS, only one call with the updated title.  

**To Reproduce:**
check onLoadEnd behavior on Android and IOS.

**Expected behavior:**
Should only be called once when load finishes. 

**Environment:**
 - OS: MAC
 - OS version: 10.14.2
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.3

**Comment by anhduy5689h** [comment]
Do you have any solutions for this issue?

**Comment by PidoMN** [comment]
Same here, any solution?

**Comment by AlexNolasco** [comment]
I came across the loading twice, if you `console.log(e.nativeEvent);`, you'll notice the `loading: true|false` hence the double call?

```{loading: false, canGoForward: false, title: "", url: "http://localhost:3000/en", target: 15257, …}
canGoBack: false
canGoForward: false
loading: false
target: 15257
title: ""
url: "http://localhost:3000/en"

canGoBack: false
canGoForward: false
loading: true
navigationType: "other"
target: 15257
title: ""
url: "http://localhost:3000/en"```

**Comment by chhornponleu** [comment]
try this
```javascript
const loaddedCalled = useRef(false);
...
<WebView
    onLoadEnd={() => {
        if (loaddedCalled.current) {
                return;
        }
        loaddedCalled.current = true;
       
        ...the rest
    }}
/>
    

           

```

**Comment by vickz84259** [comment]
For anyone encountering this, I have been able to identify that this issue occurs on 32 bit android emulator images. If you take a project that uses the webview and run it on Android 11 (API Level 30), the last android version with 32 bit emulator images, `onLoad` gets called twice. However running the same project on the 64 bit image of the same Android version and `onLoad` only gets called once. 

I am yet to identify what exactly in the 32 bit versions is causing this.

**Comment by vickz84259** [comment]
So, some further context. I traced the issue to be that `onPageFinished` in the Java WebViewClient is being triggered twice for some unknown reason in 32 bit OS versions. 

If you search on Google for "onPageFinished called twice" you'll see that a majority of the issues are from around 2011 - 2013 around when 32 bit Android was prevalent. Before 64 bit version support came with Android 5.0 (Lollipop).

This [comment](https://github.com/react-native-webview/react-native-webview/issues/343#issuecomment-524122572) links to a [stackoverflow comment](https://stackoverflow.com/a/14611465) that states that `onPageFinished` is unreliable for telling if a page has finished loading.

With that in mind and looking at the [RNCWebViewClient.java](https://github.com/react-native-webview/react-native-webview/blob/df8b47f74a5fa982276e155a4c2e52a3c8edc0fe/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java) file, in particular this [line](https://github.com/react-native-webview/react-native-webview/blob/df8b47f74a5fa982276e155a4c2e52a3c8edc0fe/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewClient.java#L318), we can see that the first time `onLoad` will get triggered `loading` will be `true` and the second time it gets triggered it will be `false` since progress will be 100.

So in your `onLoad` handler, you can check if the `nativeEvent` object for whether  the `loading` property is `true` or `false`.

Just providing this context for anyone in the future who encounters this.
