### ISSUE TITLE
[iOS] How to disable the default context menu, but still be able to select text ?

### ISSUE THREAD

**Issue by adkaushik** [react-native-community/react-native-webview#1183]
The CSS property -webkit-touch-callout seems to be not working, and -webkit-user-select: none; disables the text selection completely. Is there a way to select the text but hide the context menu ?

**Comment by poltak** [comment]
Did you get anywhere with this @adkaushik ? I've just encountered this today. Haven't found any solutions yet. The CSS in #1117 don't seem to change anything for me

**Comment by adrienpoly** [comment]
Same here my app is rejected by Apple because of that we are in a kid section and being able to select a word in a text field and search the web for a definition is a cause of rejection.

I tried various CSS solutions:

This one that is listed in several issues
```
 * {
  -webkit-user-select: none;
  -webkit-touch-callout: none; 
}
```
but it completely disables all `input` fields

**Comment by orchardfruit** [comment]
Is there any solution to this problem?

**Comment by JoshuaPariona** [comment]
This worked for me: I created an extension for WKWebView and overrode the `canPerformAction` function to always return false. This way, the webview remains selectable, but the context menu doesn't appear.


```
import WebKit
import UIKit

extension WKWebView {
    open override func canPerformAction(_ action: Selector, withSender sender: Any?) -> Bool {
        return false
    }
}
```
