### ISSUE TITLE
Tracking Issue: Fabric support

### ISSUE THREAD

**Issue by shirakaba** [react-native-community/react-native-webview#1202]
In the PR #1102, @TheSavior detailed the state-of-the-art for supporting Fabric (which had implications for long-term Animated support). We ended up discussing it in depth, so that thread should be considered prior reading to explain what aspects of the library are impacted, what changes are necessary, and why. In short:

* Fabric doesn't have `findNodeHandle` anymore.
* It has always been confusing, for many APIs, whether users need to obtain a ref to a class component instance, a ref to the host component, or a node handle to the host component.
* The `react-native-webview` library is particularly complex in this respect because `<WebView>` renders a `<View>` with a `<NativeWebView>` child, which itself has scrolling behaviour (which incidentally will differ between macOS and iOS because the iOS WKWebView has a UIScrollView, yet the macOS WKWebView doesn't contain a scrollView at all). There are valid reasons for a user or library (e.g. Animated/Reanimated) to require a ref to any of these various components.
* Fabric's approach is to ref-forward to the native component, then [adorn it](https://github.com/facebook/react-native/blob/7813e24cdb55b0716df019edc0d875730bf65169/Libraries/Components/TextInput/TextInput.js#L1042-L1044) with public APIs from the class component that wraps it.

I began work on a branch to change the way refs are managed in this library to make this Animated support compatible with Fabric. However, I found that a rather large refactor was entailed, so I've decided to separate the PR from immediate Animated support and open the issue of Fabric support in general for proper discussion.

[`shirakaba/animated-support-fabric`](https://github.com/shirakaba/react-native-webview/tree/shirakaba/animated-support-fabric) is the branch. Note that the aspect of Animated support only constitutes three lines of code: the `getScrollableNode` aspect. The rest is all related to Fabric. Note also that I've only touched the iOS implementation so far in this!

Note that this work is untested and may be missing some aspects; it's merely my best understanding of how to implement the suggestions by @TheSavior. Hopefully it can illustrate the idea in mind.

I guess a starting point is to ask @TheSavior whether this implementation essentially looks correct for iOS?

Questions for the maintainers would be what they think about this ref-forwarding and adorning process and whether it means any breaking changes in the library and ecosystem around it.

**Comment by TheSavior** [comment]
FWIW, this doesn't necessarily have anything to do with Fabric. We think these are just cleaner APIs even for React Native today. Fabric's removal of findNodeHandle doesn't require these changes, it just makes the cleaner API even nicer.

It's also worth noting that doing this isn't the only thing required to support Fabric. There will be documentation for the native changes required as it gets closer. 

The comment about `getScrollableNode` being removed in a future release isn't really related to Fabric either. That call in Animated only exists as an implementation detail to work with ScrollView. Defining that method in WebView in order to get the same behavior is essentially like depending on internals. Once we change ScrollView to have the cleaner APIs and not need `getScrollableNode`, we will no longer need that check in `createAnimatedComponent`, at which point things would break here. 

All that said, yep, your changes to iOS look good to me. I'm not sure how this pattern should get typed in TypeScript but I imagine Microsoft and the TypeScript team will need to work on figuring it out as 0.62 rolls out. In fact that issue is being tracked here: https://github.com/facebook/react-native/issues/27997

**Comment by kartikmittal1996** [comment]
Hey @shirakaba @TheSavior , please let me know if there is any working version of **react-native-webview** that will support react native new architecture with fabric. I have to migrate my application to new architecture with fabric enabled so it's a must for me before proceeding further. Thanks in advance.

**Comment by thiavila-sigma** [comment]
I'm with @kartikmittal1996. I've just changed my whole application to Fabric, and react-native-webview would play a key role in this new version. I wish I had the knowledge to help you out, but if there is anything that is within my reach, feel free to ask. 

I know @Titozzz has worked in this also. More details here: https://github.com/react-native-webview/react-native-webview/pull/2686
