### ISSUE TITLE
How to address WebView SSL Error Handler alerts in your apps.

### ISSUE THREAD

**Issue by baranoveyy** [react-native-community/react-native-webview#1228]
We receive the warning you see in the title.

Your app is using an unsafe implementation of WebViewClient.onReceivedSslError handler. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability.
We just use react-native-webview

**Screenshots/Videos:**

**Environment:**
 - react-native version: 60.5
 - react-native-webview version: 8.0.3

**Comment by baranoveyy** [comment]
<img width="757" alt="Screen Shot 2020-02-24 at 20 38 34" src="https://user-images.githubusercontent.com/12908366/75176669-a4f37500-5745-11ea-88e0-d5ca40bb94e3.png">

**Comment by BassT** [comment]
[Android documentation](https://developer.android.com/reference/android/webkit/WebViewClient.html#onReceivedSslError(android.webkit.WebView,%20android.webkit.SslErrorHandler,%20android.net.http.SslError)) says that ignoring SSL errors might get your app rejected. However, the default is to cancel requests, when SSL fails. And I don't see any overrides by `react-native-webview`.

**Comment by baranoveyy** [comment]
So why did i received this alert which adressed to RNCWebviewClient? if it is not from react-native-webview, which library is it from? do you have any opinion? thx by the way

**Comment by baranoveyy** [comment]
it is not from react-native-webview, a different 3d party aar lib

**Comment by mariod3w** [comment]
> it is not from react-native-webview, a different 3d party aar lib
@baranoveyy 
I have the same problem, could you tell which was the library that presented this error?

Thanks

**Comment by mariod3w** [comment]
> it is not from react-native-webview, a different 3d party aar lib



I have the same problem, could you tell which was the library that presented this error?

Thanks

**Comment by ahelord** [comment]
I have the same problem,, an update?

**Comment by baranoveyy** [comment]
> > it is not from react-native-webview, a different 3d party aar lib
> 
> I have the same problem, could you tell which was the library that presented this error?
> 
> Thanks

Kobil

**Comment by Pandit2903** [comment]
I am Facing same issue Google Reject my app due to this issue

I see that you have resubmitted a new submission, however, your app still violates the Device and Network Abuse policy. Your app (Version Code: 1025) is currently using the following vulnerable implementation of SslErrorHandler:

Lcom/reactnativecommunity/webview/RNCWebViewManager$RNCWebViewClient;
Unfortunately I'm not able to comment on your planned implementation. You may refer to Support page under 'Webview SSLErrorHandler' section of Help Center page for additional guidance.


Hello Google Play Developer,

We rejected WebExample, with package name com.webexample, for violating our Device and Network Abuse or User Data policy. If you submitted an update, the previous version of your app is still available on Google Play.

This app uses software that contains security vulnerabilities for users or allows the collection of user data without proper disclosure.

Below is the list of issues and the corresponding APK versions that were detected in your recent submission. Please upgrade your app(s) as soon as possible and increment the version number of the upgraded APK.

Vulnerability	APK Version(s)	Past Due Date
SSL Error HandlerFor more information on how to address WebView SSL Error Handler alerts, please see this Google Help Center article.	1025	August 31, 2021
Please follow the given steps to deactivate non-compliant app bundles or APK

Sign in to your Play Console and go to the track with the policy issue (Internal / Closed / Open testing / Production).
Click "Manage track" and "Create new release"
If the release with the violating app bundles / APKs are in a draft state, discard the release.
Otherwise, add the policy compliant version of app bundles / APKs.
Make sure the non-compliant version is under the Not Included section of this release.
Enter a release name and click Save. Once saved, click "Review release" and then proceed to roll out the release to 100%.
If the non-compliant versions are released to multiple tracks, repeat step 5 in each track.
To confirm you’ve upgraded correctly, submit the updated version of your app to the Play Console and check back after five hours to make sure the warning is gone.

While these vulnerabilities may not affect every app that uses this software, it’s best to stay up to date on all security patches. Make sure to update any libraries in your app that have known security issues, even if you're not sure the issues are relevant to your app.

Apps must also comply with the Developer Distribution Agreement and Developer Program Policies.

If you feel we have made this determination in error, please reach out to our developer support team.

Best,

The Google Play Team

package.json :
"react": "16.9.0",
"react-native": "0.61.4",
"react-native-webview": "11.6.1",

**Comment by saiaravindhan** [comment]
facing the same issue, getting a warning from google play for unsafe implementation of WebViewClient.onReceivedSslError handler
any update on the solution.
Note: in my code i haven't implemented the onReceivedSSLError().
