### ISSUE TITLE
AR Quick Look not opening USDZ files

### ISSUE THREAD

**Issue by aviggiano** [react-native-community/react-native-webview#1242]
**Bug description:**

This  webview implementation does not open correctly [AR Quick Look](https://developer.apple.com/documentation/arkit/previewing_a_model_with_ar_quick_look) URLs containing reference to USDZ files. Instead of previewing the 3D model, it opens the zip file in binary format, which is not what is intended. 

This is probably due to the use of WKWebView instead of SFSafariViewController, since [this reference](https://webkit.org/blog/8421/viewing-augmented-reality-assets-in-safari-for-ios/) states that AR Quick Look does not work with WKWebView.

**To Reproduce:**

[ar-quick-look-bug](https://github.com/aviggiano/ar-quick-look-bug)

**Expected behavior:**

Opening an AR preview of the 3D model, similarly to what happens on [Safari](https://developer.apple.com/augmented-reality/quick-look/) 

**Screenshots/Videos:**

![IMG_63573CD428D0-1](https://user-images.githubusercontent.com/3029017/75686457-0c944d80-5c7b-11ea-8a67-634d5bd2b0d4.jpeg)

**Environment:**
 - OS: iOS
 - OS version: iOS 13.3.1
 - react-native version: 0.61.4
 - react-native-webview version: 7.4.3

**Comment by Mikilll94** [comment]
I think that WKWebView supports USDZ files because I have run this JavaScript code:

![Screenshot 2020-03-18 at 17 21 53](https://user-images.githubusercontent.com/17653648/76982992-f81fa880-693c-11ea-9fe6-9896b7be8725.png)

from this website https://webkit.org/blog/8421/viewing-augmented-reality-assets-in-safari-for-ios/

And it returned `true`.

**Comment by aviggiano** [comment]
Interesting, that contradicts with the text saying

> Other than Safari, the AR integration is available in SFSafariViewController clients. We’ve also received requests to add it to WKWebView.

Were you able to test the repository I created to reproduce this issue? Since it uses `react-native-webview`, which uses `WKWebView`, which causes a bug, I concluded that it is the root cause.

**Comment by Mikilll94** [comment]
@aviggiano 
No, I did not test your repository, because I am using WKWebView in Xamarin project. However, I have the same problem as you. I cannot find any evidences that WKWebView supports or doesn't support USDZ files.

I.e. this Apple document
https://developer.apple.com/documentation/arkit/previewing_a_model_with_ar_quick_look
says that:

"When the user clicks the link in Safari or within **a web view** that's displayed in your app, iOS presents your scene in an AR Quick Look view on your behalf. For more information, see"

Could you check in React Native what returns this of chunk of code which I have pasted above? I am curious about that. Because in Xamarin.Forms it returns `true`.

**Comment by sercanov** [comment]
I also had the same output as @aviggiano

**Comment by aviggiano** [comment]
I'm still facing this issue.
Does any contributors have any ideas?

**Comment by mixed** [comment]
@aviggiano 

To do this, you need to change the iOS webview from WKWebView to SFSafariViewController.
https://webkit.org/blog/8421/viewing-augmented-reality-assets-in-safari-for-ios/

> Other than Safari, the AR integration is available in SFSafariViewController clients. We’ve also received requests to add it to WKWebView.

**Comment by aviggiano** [comment]
@mixed thank you for helping
Do you know how do I do that while using this module? N

**Comment by mixed** [comment]
@mixed 
You can solve this problem by opening the file(usdz) downloaded from WKWebView with the default viewer.

**Comment by fabdrol** [comment]
@mixed how do we do that?

**Comment by sarevok89** [comment]
Is there any update on this issue? I see it's more than 1 year old but still without a solution.

**Comment by Matiassimone** [comment]
The issue continues in the last version , anything can get any solution to that ?

![image](https://user-images.githubusercontent.com/28985499/219382016-c0f996d7-5891-424b-8ab2-3b71d531e3db.png)

**Comment by Matiassimone** [comment]
I re open the discussion,
Please any person that have the same problem or have any idea to solved that, can it's welcome to left a comment in the new open issue : https://github.com/react-native-webview/react-native-webview/issues/2860

**Comment by vulamavi** [comment]
Anyone can hire me to solve this problem
