### ISSUE TITLE
injectedJavaScript stopped working after 9.0.0

### ISSUE THREAD

**Issue by redpandatronicsuk** [react-native-community/react-native-webview#1260]
**Bug description:**

The `injectedJavaScript` parameter no longer works.

**To Reproduce:**

This used to work:

```
<WebView injectedJavaScript={`try{var audioCtx = new (window.AudioContext || window.webkitAudioContext)();
  var oscillator = audioCtx.createOscillator();
  oscillator.type = 'sine';
  oscillator.frequency.setValueAtTime(420, audioCtx.currentTime);
  oscillator.start();
  var oscillator_volume = audioCtx.createGain();
  oscillator_volume.gain.linearRampToValueAtTime(1, 0);
  oscillator.connect(oscillator_volume);
  oscillator_volume.connect(audioCtx.destination);
  }catch(e){}
  true;`} />
```

but no longer does.
**Expected behavior:**

That the above js code gets ejected into the WebView, executes and plays the sound created by the oscillator.

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by safaiyeh** [comment]
cc @shirakaba this is probably related to your PR

**Comment by shirakaba** [comment]
Does the problem remain even if you provide an `onMessage` parameter? That was a restriction of the original implementation as well.

**Comment by shirakaba** [comment]
Additionally, this example lacks a `src` prop, so I have no confidence that it reflects the exact code you’re having an issue with. Could you please provide a minimal working example for investigation?

**Comment by redpandatronicsuk** [comment]
@shirakaba Thanks, when passing an empty function to `onMessage` it works again.

**Comment by plaa** [comment]
I had the same issue, and yes, adding an empty `onMessage` function fixed the issue. But this is documented nowhere! The `injectedJavaScript` documentation should have a big red box saying that you need to define `onMessage` as well in order for this to work.

It should also be trivial to check that if `injectedJavaScript` is defined but `onMessage` is not, then add an empty `onMessage` in the lib itself, which would fix this issue once and for all.

Please open this issue and fix it or at least document it.

**Comment by shirakaba** [comment]
@plaa It's documented in `docs/Guide.md`, in the section [`The window.ReactNativeWebView.postMessage method and onMessage prop`](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#the-windowreactnativewebviewpostmessage-method-and-onmessage-prop):

<img width="831" alt="image" src="https://user-images.githubusercontent.com/14055146/78121267-1ab4c580-7403-11ea-97e0-0f3339ea5fd6.png">

This is of course no consolation. I lost hours tripping up on this myself the first time I started using this package, because that part of the docs is hidden away and there's no similar warning in the API docs.

I see no reason why lack of `onMessage` should abrogate JS injection, other than the fact that it's *always* behaved like this.

Here is what's causing it (note: I'm less familiar with Android):

* [`src/WebView.ios.tsx#L339`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/src/WebView.ios.tsx#L339) `messagingEnabled` is set to `false` only if `onMessage` is defined.
* [`src/WebView.macos.tsx#L320`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/src/WebView.macos.tsx#L320) `messagingEnabled` is set to `false` only if `onMessage` is defined.
* [`src/WebView.android.tsx#L329`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/src/WebView.android.tsx#L329) `messagingEnabled` is set to `false` only if `onMessage` is defined.
* [`src/WebView.windows.tsx#L235`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/src/WebView.windows.tsx#L235) `messagingEnabled` is set to `false` only if `onMessage` is defined.
* [`ios/RNCWebView.m#L1249-L1254`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/ios/RNCWebView.m#L1249-L1254): the `injectedJavaScriptBeforeContentLoaded` and `injectedJavaScript` user scripts do not get added if `messagingEnabled` is `false` (my own FIXME recommendation appears above these lines).
* [`android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L1058-L1062`](https://github.com/react-native-community/react-native-webview/blob/9fbcedd6b88af631edbc3d455339b3072a4aa0ea/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L1058-L1062): Addition and removal of JS interfaces are toggled by the state of `messagingEnabled`.
* I can't find references to `messagingEnabled` in `windows/ReactNativeWebView`. Maybe I'm just looking in the wrong places, or maybe JS injection isn't supported at all on Windows, yet?

This is certainly worth filing an issue for, and I would love it to be fixed.

**Comment by SRandazzo** [comment]
The messaging behavior should be resolved here which has landed in the latest release: https://github.com/react-native-community/react-native-webview/pull/1286

**Comment by shirakaba** [comment]
Now tracked in #1311.
