### ISSUE TITLE
No types for window.ReactNativeWebView ?

### ISSUE THREAD

**Issue by Baterka** [react-native-community/react-native-webview#1269]
WebView creates new object in guest's `window` called `ReactNativeWebView`, so we can call:
`window.ReactNativeWebView.postMessage(message: string)`

Are there any TypeScript Types for this `ReactNativeWebView` object?
I am not really satisfied with `declare const window: any;` approach.

EDIT: Sorry for incorrect label, please change it.

**Comment by shirakaba** [comment]
@Baterka I wrote these typings for use with iOS. Can't comment on how consistent they are with Android. Android may well differ.

```typescript
// react-native-webview-message-handlers.d.ts
declare const webkit: Webkit;

interface Window {
    webkit: Webkit;
    /**
     * A convenience API that we seem to show up in iOS.
     * Not sure whether Android does the same.
     * @see: https://github.com/react-native-community/react-native-webview/blob/25552977852427cf5fdc7b233fd1bbc7c77c18b0/ios/RNCWebView.m#L1128-L1146
     */
    ReactNativeWebView: {
        postMessage(msg: string): void;
    };
}

interface Webkit {
    messageHandlers: {
        /**
         * Added due to our call to addScriptMessageHandler.
         * @see: https://github.com/react-native-community/react-native-webview/blob/25552977852427cf5fdc7b233fd1bbc7c77c18b0/ios/RNCWebView.m#L1244
         */
        ReactNativeWebView: {
            postMessage(message: string): void;
        }
        /**
         * Added due to our call to addScriptMessageHandler.
         * @see: https://github.com/react-native-community/react-native-webview/blob/25552977852427cf5fdc7b233fd1bbc7c77c18b0/ios/RNCWebView.m#L214
         */
        ReactNativeHistoryShim: {
            postMessage(message: string): void;
        }
    }
}
```

For any readers coming across this issue: Please note that this corresponds only to the WebView's interior JS Context, not the JS Context of your React Native app (which doesn't even have a `window` object... until you connect a debugger, technically). When adding these types to your project, be careful not to be fooled into thinking that the React Native JS context has a `window` object or a globally accessible `webkit` variable.

Due to the higher likelihood of causing confusion with the React Native JS Context's global typings than helping users understand what APIs are available in their WebView JS Context, I would strongly argue against bundling these typings into the `react-native-webview` project.

Hope these help!
