### ISSUE TITLE
Unsupported browser error

### ISSUE THREAD

**Issue by nikesh8** [react-native-community/react-native-webview#1288]
Hi, I am getting an error of unsupported browser while I'm opens a url. Please see attached screen shot. Can you please please provide solution to overcome this problem which I am facing?
Please see attached screen shot.

"react-native-webview": "5.8.0"
"react": "16.8.3"
"react-native": "0.59.10"
"node": 12.5.0
"npm":  6.9.0
![screenshot-1585824785980](https://user-images.githubusercontent.com/55312626/78242076-07872000-74ff-11ea-954b-7df4bc6ff6d1.jpg)

@imownbey @alloy @tijs @jermaine @gnprice

**Comment by alloy** [comment]
This looks like an issue with the web application at the URL you are trying to reach throwing up a modal screen with this warning, rather than with the webview itself.

Either update the web application, if you have control over it, or see if changing the webview’s `User-Agent` to that of a supported browser bypasses the warning (although there’s no guarantee the web application will actually work well) https://github.com/react-native-community/react-native-webview/blob/v9.0.2/docs/Reference.md#useragent

PS: Please don’t @ mention random people when filing issues 🙏
