### ISSUE TITLE
White Screen in React Native web

### ISSUE THREAD

**Issue by chayancbnits** [react-native-community/react-native-webview#1307]
react-native-webview is working fine in android and ios but when I was the view in the web it is showing the white screen, I am providing an example URL

https://snack.expo.io/@chayancbnits/webview-example

**Comment by shirakaba** [comment]
React Native Web fundamentally cannot support the WebView component. Webpages cannot embed a WebView inside themselves (an iframe is not the same thing), so I don’t know what you’re expecting to RNW to render here.

**Comment by RWOverdijk** [comment]
Would be cool if it did somehow fall back to an iframe though. 😄

**Comment by shirakaba** [comment]
All sorts of things don’t work in an iframe. JS injection, lifecycle callbacks, cookie management, and functions like `goBack()` all wouldn’t work (to name but a few). I’m not even sure whether you could show a static snippet of HTML in it. You may also fall afoul of cross-domain security issues.

So although it’s the closest analogy that web has, it has so little coverage of this project’s APIs that it would fit too few use-cases to bother supporting.

**Comment by shivaTammana** [comment]
@chayancbnits This solution might help. https://github.com/react-native-community/react-native-webview/issues/76#issuecomment-554590908

In the solution, the below line indicates that WebView is an alias (defined in webpack / babel config) for **react-native-web-webview**
`import WWebView from 'WebView';`

**Comment by RWOverdijk** [comment]
I actually got most things working atm. Injecting is possible through the window, messages still work (even better than webview imo) and navigating is also possible through the same methods provided it's on the same origin (so there's definitely that restriction). I could see this as a community "plugin" instead of ootb support.

**Comment by shirakaba** [comment]
> I actually got most things working atm.

@RWOverdijk There are all sorts of further tediously dull things that a proper WebView can do that an iframe can't, such as multi-frame JS injection (admittedly not supported on Android), timing the JS injection such that it's before/after load, adding user script handlers, enforcing navigation policies (e.g. special handling if the URL is a PDF, and preventing users navigating off the page), and disabling scrolling/zooming... the list goes on until you've covered every public WebKit API.

I agree that any effort on producing React Native WebView for Web should best be handled outside of `react-native-webview` because – due to the fundamental impossibility of achieving API equivalence – it would ultimately be a "best of a bad job" no matter what, and it would just attract a pile of unsolvable issues. At best, `react-native-webview` should render a stub view giving some note of explanation and recommending users who need a Web implementation to handle it in a bespoke way that can better fit their use case.

I don't want to be a killjoy, but my fear here is having to constantly keep a pile of best-approximation hacks and already-lengthy documentation up-to-date with each new feature addition for the other platforms. Preventing regressions is getting increasingly hard with the number of platforms we're now supporting, but those platforms at least have an eventual hope of API equivalence.

**Comment by shirakaba** [comment]
Alternatively, somebody could file an RFC establishing:

* how each API might be implemented
* which APIs would be missing
* what concrete use-cases the React Native WebView for Web would address that a simple `iframe` alone wouldn't
* to what extent the community feel a need for a Web implementation

... and we could get a better picture of whether it's worth the effort to attempt to build and maintain an official Web implementation.

**Comment by RWOverdijk** [comment]
@shirakaba Oh you kill-joy! You broke my tender heart into a million pieces. :(((((

For real though, I get it. And I agree. If I were you I wouldn't go for an official implementation. If it would just render an iframe with a big-ass warning (in the docs) saying _"this is all it does. Here's a ref to the iframe, knock yourself out"_ that'd probably serve a large portion of the users anyway. It's stuff like FAQs and whatnot that just gets rendered so... No harm there.

Anything beyond that is probably best solved with your own solutions anyway. And the plugin I was talking about could just be a set of helpers (like the message posting I was talking about earlier).

**Comment by shraddha360** [comment]
For IOS background color black the screen flickers for nanosec with white color
