### ISSUE TITLE
printing

### ISSUE THREAD

**Issue by rockneverdies55** [react-native-community/react-native-webview#1309]
Trying to print an html element's content using the os print dialog. I have the following code snippet that launches the print dialog with expected content in the device browser.
```js
    const printContent = document.getElementById('print-container');
    const prtFrame = document.getElementById("iframe_to_print").contentWindow;
    prtFrame.document.open();
    prtFrame.document.write(printContent.innerHTML);
    prtFrame.document.close();
    prtFrame.focus();
    prtFrame.print();
```
However nothing just happens within react-native app using the webview.
- webview version: 8.1.0
- react-native: 0.61.5

Looks like something is preventing the system print dialog from showing up in the app. 

Is there a step that I'm overlooking or another known way of doing printing in webview?

**Comment by HannesOberreiter** [comment]
Can confirm `window.print()` does not work inside react native webview for android. The "normal" android chrome browser does support `window.print()`.

Cheers
Hannes

**Comment by hkar19** [comment]
does anyone find any solution?

**Comment by TinJenda** [comment]
Does anyone find any solution? This seems to be a difficult problem

**Comment by macdigger** [comment]
+1. Would be nice to find a solution…

**Comment by TinJenda** [comment]
I had tip:
I used postMessage event of react-native-webview to send data to native app, then used react-native-print lib to print as desired

**Comment by macdigger** [comment]
Thanks! 

Unfortunately what I need to do is printing a PDF file shown inside web view. 

Doesn't seem possible to fetch its data from web view using messaging. Because it's a PDF, not HTML content. 

I probably need to download the PDF and use some sort of library to display it separately from web view, and print it out. Buy so far I could only find some commercial solutions without even pricing announced. I'm currently researching this approach but no clear solution yet. 

I can't even open PDF inside OS browser because it requires some specific authentication color to be set before PDF can be served to a user :(

Would've been nice to just be able to have a print command 🤷‍♂️

**Comment by abdullah-mylobby** [comment]
> I had tip: I used postMessage event of react-native-webview to send data to native app, then used react-native-print lib to print as desired

Have you got it working ?
