### ISSUE TITLE
Offline webview(cache) support

### ISSUE THREAD

**Issue by RasAlGhul1** [react-native-community/react-native-webview#1387]
Is there anyway to show the cached version when there is no internet? At the moment it shows only an error that there is no internet.

```
      <WebView
        cacheMode="LOAD_CACHE_ELSE_NETWORK"
        cacheEnabled
        sharedCookiesEnabled={true}
        startInLoadingState
        onError={() => console.warn("error")}
        source={{
                uri: "http://google.nl",
              }
        }
      />
```

**Comment by liudmyla-schastlyvets** [comment]
Any updates here?

**Comment by RasAlGhul1** [comment]
No, sounds like no one has done this yet?

**Comment by liudmyla-schastlyvets** [comment]
@RasAlGhul1, how did you solve the problem?

**Comment by cernadasjuan** [comment]
It may be very useful

**Comment by Chasty** [comment]
I need offline support for WebView, still no answers??

**Comment by wflanagan** [comment]
Hello all, 

So, this problem is something that's been plaguing us for more than a year now. 

The case fo this to be reopened, and fixed, is this: When a person is using your app on Wifi, and they then switch to their phone's internet (everyone's phone does this several times a day), the applications built on this tech momentarily "error." Our customers see this, and complain about it.

Yes, when the connection is re-established, the app will reload.  And, yes, we've implemented custom logic that will show a nicer error than the one that shows by default. BUT, why show the error at all if the page can simply continue to be shown, or be reloaded from the cache?

**Comment by wflanagan** [comment]
Hello all,

So, this problem is something that’s been plaguing us for more than a year now.

The case for this to be reopened, and fixed, is this: When a person is using your app on Wifi, and they then switch to their phone’s internet (everyone’s phone does this several times a day), the applications built on this tech momentarily “error.” Our customers see this, and complain about it.

Yes, when the connection is re-established, the app will reload. And, yes, we’ve implemented custom logic that will show a nicer error than the one that shows by default. BUT, why show the error at all if the page can simply continue to be shown, or be reloaded from the cache?
