### ISSUE TITLE
Not compatible for BigBlueButton 

### ISSUE THREAD

**Issue by akhilsanker** [react-native-community/react-native-webview#1483]
Hi,
We are using '[BigBlueButton](https://bigbluebutton.org/)' in our web application and I need the same to work from mobile application using webview.
But on loading the url in webview its saying the browser is not compatible and need to update the browser and a message `You must have the BigBlueButton  HTML5 client installed to use this API demo`.

**Describe the solutions you came up with**
Is there anything that need to handle from mobile side?

**Comment by owattenmaker** [comment]
it's not react-native-webview's fault it doesn't work, so i'm unsure of why you're posting it here.

apple does not provide the necessary api's to access the camera from inside a web view, (and i believe webRTC is disabled, though i'd have to check on that), which is why your software claims the browser is unsupported: because it is.

if your application has other things and a small section of it is just the video conferencing, you could link out to open in the actual web browser, then have your users come back to the app once they're done

**Comment by tejastank** [comment]
With react-native, solution

add userAgent prop in webview

<WebView
    userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"

  ...otherProps
/>


add the permission for MODIFY_AUDIO_SETTINGS and other as resources needs for bigBlueButton

Thanks,
SnippetBucket.com
