### ISSUE TITLE
How to catch web request in React Native app using webview?

### ISSUE THREAD

**Issue by bluesky93128** [react-native-community/react-native-webview#1498]
I want to catch the ajax call request header when the user clicks a button.

But I can't catch the http request event.

Does anyone know how to do this?

Please help me...

**Comment by bluesky93128** [comment]
still searching for solutions

**Comment by gabriel-tentaculo** [comment]
@bluesky93128 did you ever find a solution to this? I'm also looking for.
People told me to use wireshark to intercept all communication from/to the app and its webview, but I could not configure wireshark yet to do so because I need to inspect encripted HTTPS login traffic and seems quite complex to setup.

**Comment by bluesky93128** [comment]
Sorry, I couldn't find the solution.
So I gave up to use react-native-webview, and build my own components.

**Comment by gabriel-tentaculo** [comment]
@bluesky93128 thanks for the reply, let me know if you can share that :+1:
