### ISSUE TITLE
Simplify the handling of navigation

### ISSUE THREAD

**Issue by maxammann** [react-native-community/react-native-webview#192]
Hello folks,
the goal of this issue is to simplify the handling of navigation events. I think it is a bit difficult to have `onLoadStart`, `onLoad`, `onLoadEnd`, `onShouldStartLoadWithRequest` and `onNavigationStateChange`. Maybe we can simplify this to: `onWebViewEvent` and `overrideDocumentLoading`

Also the concept of `originWhitelist` is a bit difficult to understand (Pages which do not match get opened by intend on android). I would just remove it and clients should handle it themselfes by using `onShouldStartLoadWithRequest`.

Another idea is to have a configuration like:
```
<WebView source={} onShouldStartLoadWithRequest={()=>{}} ios={{bounces: true}}/>
```
This would make it clear which props work on which platform.

This would introduce breaking changes. 
Please let me know what you think so we can start to create PRs :)

**Comment by jamonholmgren** [comment]
@maxammann Thanks for opening this issue! I appreciate the thought you put int oit.

I think from my standpoint that I am not in favor of breaking the current API, as that will put a lot of burden on people migrating from the core WebView to this one. While I understand what you're saying about your API design being more logical, we also have an obligation to not cause a lot of extra work to code that is already working properly. Where we break backwards compatibility, we should provide a very clear migration path and hopefully make it as simple as possible.

Perhaps you could create a thin wrapper third-party module that would consolidate the API in the way you like. Where it consumes the main WebView but provides a different API. Just a very thin wrapper to keep maintenance very easy. Or we could export it as a different name from this module, like:

```jsx
import { SimpleWebView } from 'react-native-webview'

<SimpleWebView 
  source={...}
  onWebViewEvent={...}
/>
```

I also am not sure I like the `ios={}` configuration, since the goal is to provide cross-platform compatibility. If the two platforms aren't compatible for some reason, we should open an issue and work on making them compatible, or no-op if that's not possible.

**Comment by maxammann** [comment]
Oke I understand that we probably should not break the API as this package is used quite a lot in the core still.

I understand that we should not neeed as `ios={}` object but when it comes to webviews we probably will not be able to support everything on every platform. Not sure how react-native generally thinks about this. For example the styling property `elevation` is only supported on Android.

In my opinion it makes sense to use something like `ios={}` for props which are not supported on every platform to avoid confusion.

We're probably getting even more similar sounding props :) https://github.com/react-native-community/react-native-webview/pull/209

**Comment by jamonholmgren** [comment]
It’s a great point and something we should think about for sure!

**Comment by Titozzz** [comment]
maybe name the props iOSShadow / androidElevation to avoid confusion ?

**Comment by maxammann** [comment]
I think this would work too. Maybe its better to keep the props flat.

**Comment by maxammann** [comment]
Also releated to https://github.com/react-native-community/react-native-webview/issues/8#issuecomment-468439323
