### ISSUE TITLE
Open or download files in webview not possible

### ISSUE THREAD

**Issue by udarts** [react-native-community/react-native-webview#280]
Hey guys, I am trying to open files (for ex: pdf) in a webview on Android and iOS and possible download or open them in another app (like we can with chrome or safari). But this seems not possible.
Do we know if there is a way to do this?

Cheers,

**Comment by Titozzz** [comment]
#203 As been added to Android so it should work. Are you up to date?

**Comment by udarts** [comment]
@Titozzz, I updated to the last version and added 

```
<key>NSPhotoLibraryAddUsageDescription</key>
<string>Save pictures for certain activities.</string>
``` 

to the Info.plist, so far so good. But when I click on an link, for ex, a pdf link it does nothing. When I click and hold, it shows me a popup menu, when I try to open it, again nothing happens. 

Any idea if something else needs to be added.

**Comment by smathson** [comment]
@udarts Can you be more specific about the behavior you are expecting to see on each platform? To be clear, this project isn't intended to be a browser but rather a way to embed web content inside a native app which leaves a lot of flexibility up to the developer by design.

Both platforms will happily display any file content that it knows how to when linked (i.e. https://www.irs.gov/pub/irs-pdf/f1040.pdf), but this is probably not what you want to do because it's effectively a dead-end for the user without some custom navigation solution (on iOS at least, due to no hardware back button). If the file is indicated to be a download via a `content-disposition` header, the platform behavior differs due to how each platform natively handles files. Android has a proper filesystem so we request the necessary permissions and download the file, but iOS doesn't have a native way to handle files, just a bunch of tools in the SDK for different things to do with that file.

You are free to implement whatever makes the most sense for your app. For instance, in our app when a user downloads a file it's primarily for viewing so we used https://github.com/itinance/react-native-fs and https://github.com/vinzscam/react-native-file-viewer to download the file to a temporary location and then use the QuickLook framework to display it which also gives them the optional "share" menu. We do this by intercepting the request with `onShouldStartLoadWithRequest` and launching into our own native flow.

Hope that helps!

**Comment by jamonholmgren** [comment]
As a side note, it would be interesting to have someone create a browser that uses RN WebView and published it as a package. It looks like @mfkp created one called `react-native-browser` a while back but hasn't touched it since. https://github.com/PrestoDoctor/react-native-browser

**Comment by smathson** [comment]
@MalcolmScruggs That’s a good point. In our case we are able to use an auth token that we already have saved on the native side. Credential management is just another thing you need to deal with all over the place if you are going with a hybrid native/web approach in your app.

**Comment by Dror-Bar** [comment]
@smathson 
When I try to view the link you submitted [https://www.irs.gov/pub/irs-pdf/f1040.pdf](https://www.irs.gov/pub/irs-pdf/f1040.pdf) it tried to download it without showing the content. Is there a way to view it instead?

**Comment by d-vincent** [comment]
I am able to properly download files from webviews, but I would like for them to automatically open once they have finished downloading. Could someone point me in the right direction for accomplishing this?

**Comment by smathson** [comment]
@Dror-Bar and @d-vincent my comment above explains on a high level how we accomplished this in our app, but you are going to have to implement your own solution to do it depending on what you want the user experience to be. It's outside of the scope of react-native-webview as I understand it to handle this kind of stuff automatically.

**Comment by Dror-Bar** [comment]
I ended up using the library react-native-pdf.

**Comment by arunreenamohan-creator** [comment]
please help me not possible to download the files on webiview.

**Comment by DaniGo-1** [comment]
Me pasa lo mismo, cuando intento descargar un archivo desde una WebView mi aplicación se cierra, ya le puse los permisos <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> pero aún así se cierra, alguno me puede ayudar?

**Comment by suryacaprice** [comment]
I have the same issue aswell unable to upload or download any files in webview

**Comment by mfkp** [comment]
I'm not actively maintaining this project right now so if anyone wants to do a pull request, more than welcome :-)

**Comment by ali27001** [comment]
ı have a similar problem https://forums.expo.io/t/pdf-download-problem-cant-open-url-data-application-pdf-base64/43657
