### ISSUE TITLE
postMessage instance method not documented

### ISSUE THREAD

**Issue by sgtpepper43** [react-native-community/react-native-webview#411]
I noticed there's a `postMessage` instance method on the component [here](https://github.com/react-native-community/react-native-webview/blob/master/js/WebView.ios.js#L369). It's not documented anywhere, so, is it officially supported or is it some sort of deprecated function? If it's supported, I'd be happy to write docs for it. If it's not, I'd also be happy to mark it as deprecated in the source. If it's up for debate, I'd say it feels like it could be a lot cleaner than using `injectJavascript`, since instead of letting React Native just inject whatever code it wants, you have a strict API that is defined by the client. It's also nice that it mirrors how data gets into React Native.

**Comment by tallpants** [comment]
I think it's due to be removed: https://github.com/react-native-community/react-native-webview/blob/4cbfc811958644469a354488a7e0028cec7b3266/README.md

But I'd actually argue that we document this and maintain it instead of removing it. The argument is that it's less flexible than `injectJavaScript`, but there is one major use case that `injectJavaScript` can't handle, and only `postMessage` can -- sending over dynamically generated strings from the React Native -> WebView.

Imagine an app with a webview where the app passes along credentials / token to the webview to auto-login the user into a website. There's no reliable way to pass along a string that might contain quotes (`"`, `'`, or `` ` ``) with just `injectJavaScript`, but `postMessage` can handle this just fine.

**Comment by tallpants** [comment]
@Titozzz @jamonholmgren  -- what do you guys think?

**Comment by tallpants** [comment]
It's due to be removed @sgtpepper43  -- I think it's due to be removed: https://github.com/react-native-community/react-native-webview/blob/4cbfc811958644469a354488a7e0028cec7b3266/README.md#versioning

**Comment by Titozzz** [comment]
injectJavascript offers way more flexibility. What could be done is create helpers to help people use it if it's too complicated :)

**Comment by sgtpepper43** [comment]
It's not necessarily too complicated, just a little _too_ flexible. In any other instance when asked the question "should we just pass strings down to this function and let it `eval` the code, or should we define an api?" the answer would always be to define an api. I'm not even sure how it's more flexible, I can't think of anything you can do with `injectJavascript` that you couldn't do with `postMessage` (besides being able to do it without changing the webview's source code). Obviously you _can_ write yourself a strict api, and limit your `injectJavascript` code to calling the methods, but without some guidance it seems unlikely that any newer developers would think to do that.

**Comment by Titozzz** [comment]
Many people actually inject / execute code inside the webview with this, and it would not be doable with postMessage.

**Comment by sgtpepper43** [comment]
The only reason you wouldn't be able to do it with `postMessage` is if you didn't own the source of the webview. If you own the source of the webview, you just move the code you're going to inject over to the html, and then execute it via postMessage, passing any data you need.

**Comment by Titozzz** [comment]
Once again, there is no reason to limit possibilities... 🤔 With your logic we could also remove injectedJavascript. 

> And if you don't own the source... maybe you shouldn't be injecting scripts in there

You would be surprised what people are doing with the webView 😆

**Comment by sgtpepper43** [comment]
Fair point, though it seems like there might be a good reason they don't let you inject javascript into iframes in browsers anymore 😉 

I guess my main concern is people at my own company needing to use a webview, interfacing with it poorly (since there isn't really an established pattern for doing so), and then later our app runs into problems that are hard to fix because of it. I don't know all the ways webview is currently being used, but do you think there's some common pattern out there that could be documented to help keep the api between the components clean?

**Comment by sgtpepper43** [comment]
Ohhh, yeah yeah. That would be nice.

**Comment by tallpants** [comment]
@Titozzz the only thing I can think of is having a way to pass arbitrary strings like access tokens from RN to the webview, that might be harder with inject because the token could have arbitrary characters in the string. Is there any reason in particular you're opposed to documenting and maintaining `postMessage`?

**Comment by cva-volt** [comment]
i agree with sir @tallpants  and sir @sgtpepper43; and i'm also confused about the bridge removal. 

for our use case we would like to keep the usage of the webview as transparent as possible to the ones who host it (in our case a 3rd party Card Processor) and js injection is kind of a "shady business" there 

besides, all the bridge logic goes through static code analysis;  which would have to be ignored or reinvented since inject works with strings.

Other than that thank you for your time in maintaining this lib 👍 

also the question is kind of popular #356 #323 #66

**Comment by Titozzz** [comment]
PostMessage litteraly injects JS containing the code so that you receive an event on the window object. It's a duplicate and this is the reason it was never documented. 

All the feedbacks are noted and when I remove it I'll create helpers.

**Comment by tallpants** [comment]
Good to hear, thank you @Titozzz 🎉
