### ISSUE TITLE
Question: How will the iOS WebView differ from react-native-wkwebview

### ISSUE THREAD

**Issue by f0rr0** [react-native-community/react-native-webview#43]
In my understanding, this repository has been created to extract the WebView related source code from the main `react-native` repo in an effort to make it (`react-native` repo) leaner. Also, the `UIWebView` based implementation seems to have been deprecated in favour of `WKWebView` for iOS specifically. AFAIK, the android implementation has not been altered. 

If indeed my understanding is correct, did the maintainers consider https://github.com/CRAlpha/react-native-wkwebview as a viable candidate for the iOS implementation instead of building another one? If they did consider it and decided against it, how will this `WKWebView` based implementation differ from the one in `react-native-wkwebview`?

**Comment by satya164** [comment]
AFAIK React Native's WebView supported WKWebView when this was extracted, so it wasn't needed to look at other WkWebView implementations.

I think it's better to keep this implementation under `react-native-community`. It'll also be nice if the maintainers of `react-native-wkwebview` want to merge these projects into `react-native-community/react-native-webview` so that the work isn't split.

**Comment by Titozzz** [comment]
FYI we did contact the authors to ask them if they wanted to contribute as we feel we would all benefit from one package instead of so many: https://github.com/CRAlpha/react-native-wkwebview/issues/191. I will spend some time later to understand if there is still any benefits with using their package, and if so I'll try to implement it in the community package.

WebView being extracted from core does not mean it's support getting dropped, but instead easier contribution from the community

**Comment by f0rr0** [comment]
@satya164 @Titozzz thanks for replying so quickly (that too on a Sunday).

> WebView being extracted from core does not mean it's support getting dropped, but instead easier contribution from the community

I am not worried about the support about the support being dropped. Moving this out of the core seems a step in the right direction.

> FYI we did contact the authors to ask them if they wanted to contribute as we feel we would all benefit from one package instead of so many: CRAlpha/react-native-wkwebview#191.

This is great. I hope the authors agree.

>  I will spend some time later to understand if there is still any benefits with using their package, and if so I'll try to implement it in the community package.

IMO their package is more feature rich. There seem to be issues here already referring to that other repo:
https://github.com/react-native-community/react-native-webview/issues/23
https://github.com/react-native-community/react-native-webview/issues/43

> and if so I'll try to implement it in the community package.

Does it make sense to fork the other repo under this organisation instead implementing it here again or accepting PRs porting individual features?

https://github.com/react-native-community/react-native-webview/issues/38#issuecomment-420943910

**Comment by Titozzz** [comment]
I think porting individually we will the chosen solution, have you read https://facebook.github.io/react-native/blog/2018/08/27/wkwebview ? There has been a lot merged in 0.57 for the webview, which explains sticking to the react native original implementation. A lot of bug might a been fixed by the new implem, and our work initially here we be to review all the issues IMPORTED and make sure bugs still exists.

**Comment by f0rr0** [comment]
Cool seems like the ball's in their court now. Hope they agree. I will close this thread.

**Comment by jamonholmgren** [comment]
@f0rr0 Just FYI:

https://github.com/CRAlpha/react-native-wkwebview/issues/191#issuecomment-422146121

> This project is licensed under MIT, so feel free to take part of the code or fork the whole project. And I am happy to direct the contributors to the new project.
