### ISSUE TITLE
[DISCUSSION] inter process function invocation 

### ISSUE THREAD

**Issue by kirill578** [react-native-community/react-native-webview#467]
I am working on a project where there is a requirement to reuse `react-native` code inside a `webview`. this was quite simple on a small scale. The webview post a message asking for a `token`, we get the message in react-native, find the token and send it back as a message.

This become quite a hassle, as more data has to be pulled from the react-app. I created a library that allows you to reference functions, which will injected into the webview. this supports promises (rejections in react-native will be thrown in the webview as well)

here is a small example of how it is used:

```js
export const WebViewWithBridge = withWebViewBridge(WebView);
```

```js
<WebViewWithBridge
       source={{uri: 'https://your-page.io'}}
       reactNativeApi={{
           getToken: async (type) => "foo-bar-" + type
       }}
     />
``` 

```js
const token = await this.getReactNativeApi(timeout).getToken('admin');
```

I am thinking about making a PR that will merge [react-native-webview-bridge-seamless](https://github.com/kirill578/react-native-webview-bridge-seamless) into this project. **Is there anything I should take into consideration before starting? will the community prefer it to be a wrapper package, to keep the core project smaller?**

**Comment by KoenLav** [comment]
This has been discussed and proposed before.

I also created a POC for this functionality (as a wrapper package): https://github.com/KoenLav/bridged-webview

In my opinion the seamlessness, as you names your package, we could offer is the most important thing to consider.

I'm all for adding this as it enables an easier integration between existing PWAs, or really any webapp, with React Native. 

However I don't believe this is the current position of the maintainers as well.

Would appreciate for this idea to receive some more thought and am interested in discussing the API if this idea actually gets support.

**Comment by swansontec** [comment]
I have also written a library that does this, called [yaob](https://github.com/EdgeApp/yaob). This library allows you to send arbitrary objects in both directions over any JSON-like interface, so you can implement rich API's.

We are using the library to run a full crypto-currency wallet inside the WebView, so we have a pretty massive API with hundreds of methods and dozens of objects zipping back and forth between the WebView and React Native. The yaob bridge is handling it all pretty smoothly so far. We did this because React Native doesn't have threads, so this was the best way to get the heavy crypto logic off of the UI thread.

The yaob library isn't just for React Native, though. We are also using it on the web to do cross-domain messaging in exactly the same way. Basically, anywhere that has a `postMessage` / `onmessage` interface can use it.

Since yaob is platform-neutral, it doesn't have WebView functionality baked in. I would definitely be interested in supporting an effort to build a bridge-enabled WebView.

**Comment by Titozzz** [comment]
Hello @kirill578, I really like the idea of a wrapper package as this is not everyone using webview would need and I'm trying to remove as much code as possible from this package to keep it maintainable.

However, it is completely possible to reference your packages @swansontec @kirill578  from the docs if you wish.

Btw I like the way your package hooks around webview :)
