### ISSUE TITLE
check camera permission

### ISSUE THREAD

**Issue by M45ter** [react-native-community/react-native-webview#573]
**Bug description:**
html use camera , in android log error
java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE...

**To Reproduce:**
html code like
<input type="file" accept="image/*" capture="camera">

**Expected behavior:**
open camera , take a pic and return pic to html

**Environment:**
 - OS: android 
 - OS version: 9
 - react-native version: 0.59.8
 - react-native-webview version:5.8.1

**Comment by ddenisen** [comment]
Dealing with the same issue here. The problem is that Android dictates that _if_ your app declares the "CAMERA" permission in its manifest, _then_ you must explicitly request camera permission from the user before using the IMAGE_CAPTURE intent, which the web view does. See more details [here](https://stackoverflow.com/questions/32789027/android-m-camera-intent-permission-bug) and [here](https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE).

However, if the web view is the only place where you're relying on the camera, then you can simply remove the camera permission from your manifest and it will just work. Kind of stupid API design, I know.

**Comment by sakina1403** [comment]
@ddenisen I tried removing the camera permissions but it still doesn't work. Like the chooser opens for whether to select camera/gallery, but when I press on Camera, the chooser closes and nothing happens after that.

**Comment by sakina1403** [comment]
It should ask permission at runtime, instead it just denies silently. I can confirm this because when I go to settings and change it from 'Ask' to 'Allow' then the camera opens and I am able to upload image.

**Comment by lfalkner** [comment]
I am seeing the same behavior as @sakina1403 with the following environment.
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.9 => 0.59.9 
and 
        API Levels: 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom

In addition, I can see that the permissions for the camera are granted in the emulator, when I go to the settings section.

**Comment by lfalkner** [comment]
Previously, my team was using this library:
 https://github.com/andreipfeiffer/react-native-webview-android-file-upload
I'd be open to making a PR with changes included in this library which properly handle permissions for the camera if there is interest
