### ISSUE TITLE
Certain websites result in invariant violation in custom webview

### ISSUE THREAD

**Issue by donnellycolton** [react-native-community/react-native-webview#624]
**Bug description:**
Attempting to load certain websites from a custom webview results in an invariant violation:

    Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.
    
    This error is located at:
        in RNCWebView (at WebView.android.js:205)
        in RCTView (at View.js:45)
        in View (at WebView.android.js:208)
        in WebView (at App.js:18)
        in App (at renderApplication.js:35)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:98)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:115)
        in AppContainer (at renderApplication.js:34)

**To Reproduce:**
CustomWebView.android.js:

    const RCTCustomWebView = requireNativeComponent(
        "CustomWebView",
        CustomWebView,
        WebView.extraNativeConfig,
    );
    
    export default class CustomWebView extends Component {
        static propTypes = WebView.propTypes;
    
        render() {
            return (
                <WebView {...this.props} nativeConfig={{component: RCTCustomWebView}} />
            )
        }
    }

CustomViewManager.java:

    @ReactModule(name = CustomWebViewManager.REACT_NAME)
    public final class CustomWebViewManager extends RNCWebViewManager {
        static final String REACT_NAME = "CustomWebView";
    
        protected static final class CustomWebView extends RNCWebView {
            CustomWebView(ThemedReactContext reactContext) {
                super(reactContext);
            }
        }
    
        public static class CustomWebViewClient extends RNCWebViewClient { }
    
        private ReactApplicationContext mContext;
    
        CustomWebViewManager(ReactApplicationContext reactApplicationContext) {
            super();
            mContext = reactApplicationContext;
        }
    
        @Override
        protected RNCWebView createRNCWebViewInstance(ThemedReactContext reactContext) {
            return new CustomWebView(reactContext);
        }
    
        @NonNull
        @Override
        public String getName() {
            return REACT_NAME;
        }
    
        @Override
        protected void addEventEmitters(ThemedReactContext reactContext, WebView view) {
            view.setWebViewClient(new CustomWebViewClient());
        }
    }

CustomWebViewModule.java:

    @ReactModule(name = CustomWebViewModule.REACT_NAME)
    public class CustomWebViewModule extends RNCWebViewModule {
        static final String REACT_NAME = "CustomWebView";
    
        private final ReactApplicationContext mContext;
        private Handler mHandler;
    
        CustomWebViewModule(ReactApplicationContext reactContext) {
            super(reactContext);
            mContext = reactContext;
        }
    }

App.js:

    export default class App extends Component {
        render() {
            return (
                <CustomWebView source={{uri: "https://www.facebook.com"}} />
            );
        }
    }

Compile and run on Android. See above error. Also works if loading `https://www.gmail.com`

However, this does work with other websites, for example if uri is "https://www.google.com". Also works if using `<WebView source={{uri: "https://www.facebook.com"}} />` instead of `CustomWebView`

**Expected behavior:**
Facebook and Gmail should load as expected.

**Environment:**
 - OS: MacOS Mojave
 - OS version: 10.14.15
 - react-native version: cli: 2.0.1, library: 0.59.8
 - react-native-webview version: 6.2.2
- Phone: Pixel 2 XL
- Android Build: PQ3A.190605

**Comment by donnellycolton** [comment]
This exact same error appears to happen when redirecting to another page (i.e. opening another url via a button in the source url). Not sure if related.

**Comment by caojianfeng** [comment]
It is  blocking me too.

**Comment by wisnshaftler** [comment]
i have this error what is the solution

**Comment by mathmul** [comment]
I get the very same error using the simplest of code. Without webview it works fine.
`import React, {Component} from 'react';
import { AppRegistry } from 'react-native';
import { WebView } from 'react-native-webview';

export default class test1 extends Component {
  render() {
    return (
      <WebView
        source={{ uri: 'https://www.google.com' }}
        style={{ marginTop: 20 }}
      />
    );
  }
}

AppRegistry.registerComponent('test1', () => test1);`

./android/settings.gradle
`rootProject.name = 'test1'
include ':react-native-webview'
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'`

./android/app/build.gradle
`apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.test1"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }

    packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }
}

dependencies {
    implementation project(':react-native-webview')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)`

./android/app/src/main/java/com/test1/MainApplication.java
`package com.test1;

import android.app.Application;
import android.util.Log;

import com.facebook.react.PackageList;
import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
import com.facebook.react.bridge.JavaScriptExecutorFactory;
import com.facebook.react.ReactApplication;
import com.reactnativecommunity.webview.RNCWebViewPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new RNCWebViewPackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}`

Can anyone spot the error?

**Comment by magbicaleman** [comment]
![image](https://user-images.githubusercontent.com/735039/64968621-7ad18900-d870-11e9-8781-68a45d441274.png)

Curious if anyone got this resolved. I tried running `react-native link react-native-webview` but no success.

**Comment by donnellycolton** [comment]
I wasn't able to figure this out, and my company had me move on to Cordova instead of struggling through React Native.

@magbicaleman this happened to me on Android, so that wouldn't have worked for me.

**Comment by magbicaleman** [comment]
@donnellycolton thanks for the reply, appreciate it.

**Comment by deflorilemarului** [comment]
I have same issue on IOS , started yday, loading account.google.com.
Tried all sorts of things, pod install, nom install, cleaned build folder, ran build from cmd line and from xcode - issue keeps coming.

any solution to this ?
thanks

**Comment by Jhbioco** [comment]
> ![image](https://user-images.githubusercontent.com/735039/64968621-7ad18900-d870-11e9-8781-68a45d441274.png)
> 
> Curious if anyone got this resolved. I tried running `react-native link react-native-webview` but no success.
> 
> The following worked for me: [#161 (comment)](https://github.com/react-native-community/react-native-webview/issues/161#issuecomment-441971014)
> 
> running `pod install` in the ios folder.

This worked for me.
