### ISSUE TITLE
Android Cookies not being deleted

### ISSUE THREAD

**Issue by thomasarogers** [react-native-community/react-native-webview#631]
**Bug description:**
I am implementing an OAuth2 flow for users and upon re-loading the react-native-webview with the login url after logging out on iOS devices the authorization form is displayed as it should be however incorrectly on Android devices users are taken straight into the application as if already logged in as if the Auth cookie is present. I have all the props I can see as relevant set below but still no luck. 

 cacheEnabled={false}
 incognito={true}
 thirdPartyCookiesEnabled={false}
 sharedCookiesEnabled={false}
 domStorageEnabled={false}

**To Reproduce:**
Set the source to any url which requires Auth and sets cookies such as Facebook.com. login and then reload the bundle. On iOS devices you are shown the login form, on Android devices you are logged in already.

**Expected behavior:**
 Cookies should not be set and url should ask for authentication

**Environment:**
 - react-native-webview version: 5.9.1 (6.2.2 not compatible with RN Gesture Handler)
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
      Memory: 26.05 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - /usr/local/opt/node@8/bin/node
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-git-upgrade: 0.2.7

**Comment by jpodpro** [comment]
YES! i have been fighting with this for week and was just about to finally file a but report when this came up. When i logout of my app (which clears the cookies) and then terminate, reopening shows that the cookies are still there. I tried setting the value too and came up with the same result.

Oddly enough, if i inspect the webview after logout (doing nothing but opening and closing the inspector) then the cookie behavior is correct. The inspected webview shows the correct behavior: removed cookie or empty cookie value. It's as if there are queued cookie actions that aren't being performed because the app is terminated, but get performed when the webview is inspected.

**Comment by Collin3** [comment]
Incognito is not supported on Android yet, but there is a PR to add support. You should try pulling in the changes in #524 into your app and see if that fixes your problem. If it does please tag the maintainers to try and get them to review/merge the PR, otherwise comment and let us know what didn't work. I have been using a forked version of this repo with the changes from that Android PR for over a month now and everything has been working great for me!

**Comment by jpodpro** [comment]
this is absolutely not resolved.

**Comment by Collin3** [comment]
@jpodpro, maybe I’m misunderstanding what you’re trying to accomplish, but have you tried with the latest version and setting incognito={true}?  Now that Android has support for incognito I haven’t had any issues with cookies persisting 🤔

**Comment by jpodpro** [comment]
i don't want incognito because the app needs to store various cookies to function. the problem is that android does not delete cookies in one particular scenario even though it has been instructed to do so.

**Comment by jpauldan** [comment]
this is still very much a problem in android on the latest version (11.0.0)

**Comment by jpodpro** [comment]
this is still very much a problem in android on the latest version (11.0.0)
