### ISSUE TITLE
Cookies/localStorage is not shared across WKWebView:s

### ISSUE THREAD

**Issue by epiceros** [react-native-community/react-native-webview#68]
I opened an issue here:
https://github.com/facebook/react-native/issues/21450

Is this something that needs to be addressed here as well?

**Comment by felixmeziere** [comment]
This is blocking us too :/

**Comment by epiceros** [comment]
Hi! Some more info. We have an app with one main webview where, the user logs in. Then at times we overlay that webview with another webview, where the user needs to be logged in (so they are both open at the same time, and they are on the same domain). The webview displays fine, but the user is not logged in, in the overlaying webview. This is only the case for WKWebView, in UIWebView, and on Android, it just works.

**Comment by Titozzz** [comment]
Ok, thanks for the details. I you want to start working on it I can review / merge pull requests 🚀

**Comment by Titozzz** [comment]
Good insight, thanks

**Comment by finalquest** [comment]
Me again.
We have been strugling with cookies errors on wkwebview from the start.
The way wkwebview handles cookies on iOS is pretty rare.
In the old UIWebview, the cookies are shared between all the network requests of the application.
So, for example, I logged to a server using fetch on RN, the webview can keep a session without login, because the cookie session is already setted by the first fetch.

WKWebview dosnt work like this. I've made several attempst to fix that on the react-native-wkwebview repo, but I failed every time.

So, if anyone has any insight on this, I will gladly accept it

Regards

**Comment by KoenLav** [comment]
This should already be fixed here:

https://github.com/CRAlpha/react-native-wkwebview/commit/3e0162987ac7bf4175f94625edc44565d107fe2d

Please consider replacing WKWebView with this better maintained version, per my suggestion here: https://github.com/react-native-community/react-native-webview/issues/105
