### ISSUE TITLE
WebView not found

### ISSUE THREAD

**Issue by nahidmbstu** [react-native-community/react-native-webview#720]
![67035868_2247203305502192_2172325077415100416_n](https://user-images.githubusercontent.com/25228579/61170784-29ff9480-a590-11e9-8aec-0d96e27879de.png)

System:
    OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
    Memory: 2.04 GB / 11.65 GB
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 3.5.2 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
   "react": "16.8.6",
    "react-native": "0.60.2",
    "react-native-gesture-handler": "^1.0.5",
    "react-native-webview": "^6.3.1",
    "react-navigation": "^3.11.1"
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by jayshah123** [comment]
By any change are you importing `WebView` from `react-native` instead of using `react-native-webview`?

**Comment by tarasvakulka** [comment]
Same issue, RN 0.60.3, please help

**Comment by Ivan-Stashak-CardinalPeak** [comment]
Same issue...

I'm upgrading a project to RN 0.60.3 . Unfortunately, I'm getting the following error when I attempt to run on Android:

`WebView has been removed from React Native. It can now be installed and imported from 'react-native-webview' instead of 'react-native'. See https://github.com/react-native-community/react-native-webview`

I have run 'npm install --save react-native-webview' and confirmed that it is appropriately linked into the my underlying Android project (i.e. settings.gradle, build.gradle, imports, etc...). I've also made the appropriate changes to ensure I import WebView like so:

`import { WebView } from 'react-native-webview';
`

and ensure that I've removed all occurrences of:

`import { WebView } from 'react-native;`

It compiles fine, but I get the run-time error above.

Any thoughts?

**Comment by unnhao** [comment]
`RNCwkwebview was not found` 
this problem is bothering me...

**Comment by franckboudraa** [comment]
Same issue here on fresh React Native 0.60 install

![Simulator Screen Shot - iPhone X - 2019-07-23 at 13 42 16](https://user-images.githubusercontent.com/3285571/61709598-e0f9ce00-ad4f-11e9-8a51-d7f69d2db182.png)

**Comment by tarasvakulka** [comment]
Guys, I solved this problems, by check my node_modules, I have some dependencies, that import WebView from react-native, I replace them by react-native-webview, or update packages to new version

**Comment by zodlanier** [comment]
I had the same occurrence as @Ivan-Stashak-CardinalPeak but using RN 0.60.4
@tarasvakulka can you please elaborate more on which part of the dependencies?

**Comment by tarasvakulka** [comment]
@zodlanier , I remove react-native-qrcode from node_module, that use WebView from recta-native, now I use react-native-qrcode-svg

**Comment by ASumIT2016** [comment]
![Screenshot_1571232428](https://user-images.githubusercontent.com/26159831/66923681-e614a380-f046-11e9-9bf1-30b66765e609.png)
 still searching for solutions

**Comment by alihbk** [comment]
i have the same issue
