### ISSUE TITLE
Download file on ios

### ISSUE THREAD

**Issue by MaximMatsuk** [react-native-community/react-native-webview#729]
Hello. I'm trying to download files with usual links. On android everything works perfect. On ios after click on link file preview opens. I can see my file, but i don't know how i can download it, and even can't click something like "back" button to close this preview and back to start page with link. May be there is some features that i don't know? Thanks!

**Comment by KPS250** [comment]
On Android, if file path is provided(image, pdf ,xls) it downloads its instead of showing a preview like on iOS. Any way to show file preview on Android?

**Comment by longnk-1447** [comment]
the same, please give me any solution!

**Comment by bova80** [comment]
So I guess this hasn't been fixed yet?  iOS just opens preview and there doesn't seem to be a way to go back to the WebView.

**Comment by hiennguyen92** [comment]
Hi all, please give me any solution. Without preview, only download it.

**Comment by SL-A-SH** [comment]
Any solutions yet?

**Comment by kroeberk** [comment]
I also could not find a solution. Please provide one - this only happens on iOS.

**Comment by varunshukla** [comment]
@MaximMatsuk I know it's been an year now, but it would be great to know what worked for you. And if not, then did you try any other approach?

**Comment by mdabees** [comment]
Hello, I can't seem to get this to work i know. the "onFileDownload={ ( { nativeEvent: { downloadUrl } } ) => {" has been added and i need my own code to make this work. I tried to use expo file system and expo sharing to get ti to download but it's not working. all i want is that when they downoload a pdf instead of a preview they can share the document or save it. ANy help would be greatly appreciated. 

Below is the code i tried to make it work but failed (the alert function works but then nothing happens):


export default function App() {
  let [selectedImage, setSelectedImage] = React.useState(null);

  let openImagePickerAsync = async () => {
     const downloadResumable = FileSystem.createDownloadResumable(
      {downloadUrl},
      `${FileSystem.documentDirectory}/pdf.pdf`,
      {},
    );

    const { uri, status } = await downloadResumable.downloadAsync();
    // setSelectedImage({ localUri: uri });
    Sharing.shareAsync(uri);
  };

  

  let openShareDialogAsync = async () => {
    if (!(await Sharing.isAvailableAsync())) {
      alert(`Uh oh, sharing isn't available on your platform`);
      return;
    }

    Sharing.shareAsync(selectedImage.localUri);
  };

  // if (selectedImage !== null) {
  //   return (
  //     <View style={styles.container}>
  //       <TouchableOpacity onPress={openShareDialogAsync} style={styles.button}>
  //         <Text style={styles.buttonText}>Share this</Text>
  //       </TouchableOpacity>
  //     </View>
  //   );
  // }

  return (
    <View style={{ flex: 1 }}>
     <WebView
          //onLoadStart={() => (this.showSpinner())}
          //onLoad={() => (this.hideSpinnerxx())}
          //onLoadEnd={() => (this.hideSpinnerxx())}
          style={{ flex: 1 }}
          source={{ uri: 'http://www.pdf995.com/' }}
          onFileDownload={ ( { nativeEvent: { downloadUrl } } ) => {
           
            Alert.alert(
              "Student Union Documents",
              "Do you wish to download and share this document",
              [
                {
                  text: "Download",
                  onPress: () => {openImagePickerAsync}
                },
                {
                  text: "Cancel",
                  onPress: () => console.log("Cancel Pressed"),
                  style: "cancel"
                },
              ],
              { cancelable: false }
            );}

**Comment by naveenApplikation** [comment]
any solutions?
