### ISSUE TITLE
onScroll prop with Animated.Event and useNativeDriver 

### ISSUE THREAD

**Issue by TfADrama** [react-native-community/react-native-webview#740]
**Bug description:**
I created a animated component with the webview in order to use the native driver for animations while scrolling the webview. All animations work, but when i use the native driver to have a better performance, all animations related to the webview onScroll just don't work, as if i never had created animations. Everything goes fine, without erros, but with no animations.

**To Reproduce:**
```
const AnimatedWebView = Animated.createAnimatedComponent(WebView);
(...)
<AnimatedWebView
        useWebKit
        style={styles.slideStyle}
        source={{uri: this.pageURI}}
        onShouldStartLoadWithRequest={this.handleLoadRequest}
        onScroll={
            Animated.event([{ nativeEvent: { contentOffset: { y: this.scrollY } } }],
              {
                useNativeDriver: true,
                },
              })}
/>
```

**Expected behavior:**
When i set the native driver to true the animations should work as they do when theres no native driver.

**Environment:**
 - OS: iOS
 - OS version: 12.4
 - react-native version: 0.57.8
 - react-native-webview version: npm 5.12.1

**Comment by TfADrama** [comment]
... still searching for solutions :|

**Comment by prateekchachra** [comment]
+1

**Comment by shirakaba** [comment]
I have found that – at least on iOS – `onScroll` doesn't support Animated at all:

https://twitter.com/LinguaBrowse/status/1211375582073761799?s=20

Krzysztof Magiera clarified that the scroll events aren't hooked up correctly by `createAnimatedComponent()` in this case because the WebView component (correctly) renders a WKWebView as its base component rather than its underlying UIScrollView, so we'll need to implement a workaround to forward the UIScrollView ref to `createAnimatedComponent()`:

https://twitter.com/kzzzf/status/1211604972086976512?s=20

**Comment by minhchienwikipedia** [comment]
@shirakaba How can I resolve this issue? I had `createAnimatedComponent` but it not works for me
