### ISSUE TITLE
How to send fcm token from react native to webview

### ISSUE THREAD

**Issue by rshaikhcornerstone** [react-native-community/react-native-webview#748]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by andreipfeiffer** [comment]
The way I do it, passing data to be used in WebView, is something like the following:

```
const CustomWebView = (props) => {

  const injectedCode = () => {
    const { FCMToken } = props;

    return `
      (function(key) {
        var storedToken = localStorage.getItem(key);
        if (!storedToken || storedToken !== '${FCMToken}') {
          localStorage.setItem(key, '${FCMToken}');
          location.reload();
        }
      })('FCMToken');
    `;
  };

  return (
    <WebView
      javaScriptEnabled={true}
      injectedJavaScript={injectedCode()}
      domStorageEnabled={true}
    />
  );
}
```

1. the injected JS code will be executed after page load
2. so, it cannot be used by any other script on the page
3. that's why, on first load, after I set the data in the localStorage, I reload the page
4. it's an inconvenient that only happens on first load
