### ISSUE TITLE
Android not loading a url  - inconsistent api

### ISSUE THREAD

**Issue by gilador** [react-native-community/react-native-webview#988]
**Bug description:**
there is a different api for iOS and Android 
          source={{ url: url }}   //works only on iOS
          source={{ uri: url }}   //works on Android & iOS

**Expected behavior:**
the api for both platform should be consistent   

**Environment:**
 - OS:Android
 - OS version: sdk 23+
 - react-native version: 0.59.9
 - react-native-webview version: 6.0.2

**Comment by tianweicc** [comment]
can you fixed？

**Comment by 1nfility** [comment]
+1 - This bug made me debug for over 3 hours until i found this.

**Comment by Titozzz** [comment]
We use react-native default loading capabilities, (same as for images). Using url as a parameter is not documented anywhere, has no benefits, and could be removed anytime, because no one should use it. See https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#source
