### ISSUE TITLE
Add to calendar won't work

### ISSUE THREAD

**Issue by rthombre26** [react-native-community/react-native-webview#998]
**Bug description:**

 So My webview had add to calendar event which is finely work on browser. But in webview only server request goes but no calendar event create on both android  and ios.

**Environment:**
 - OS:
 - OS version:
 - react-native version: 0.57.7
 - react-native-cli: 2.0.1
 - react-native-webview version:

**Comment by rthombre26** [comment]
Kindly help. Research and tried everything but nothing worked

**Comment by vpankov** [comment]
same issue

**Comment by safaiyeh** [comment]
Webview currently does not support ICS links, a PR is welcome to get support for this.

**Comment by SudoPlz** [comment]
@safaiyeh I'd love to contribute that because we need it as well, any guidance as to where to start?

Are there any similar contributions in the past for other file types that I can look into as an example?

Any help would be appreciated.

Thanks

**Comment by Andriiklymiuk** [comment]
Has someone figured out how to make it work?

**Comment by Nikooos** [comment]
I'm curious as well...

**Comment by tholmgren** [comment]
Any update on this?  I'd be interesting in help out if someone can point me in the right direction.

**Comment by mustafashabib** [comment]
I know this is old but are you asking about opening `data:text/calendar...` links in the react native webview? I believe we came across this issue as well. Our solution was as follows 

```typescript
import { Linking } from "react-native";
import WebView from "react-native-webview";

function onShouldStartLoadWithRequest(request: { url: string; isTopFrame: boolean }): boolean {
        if (request.url.startsWith("data:text/calendar")) {
            //force opening data links in the native web browser so
            //that normal OS level Calendar app intercepts it 
            Linking.openURL(`https://yourapp.com/open-native-app?url=${request.url}`);
            return false;
        }
}
<WebView /*...your properties...*/
                    onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
/>
```

By using `Linking.openURL` and passing a URL you control (in this example `https://yourapp.com/open-native-app?link=...`) it will open that URL in the native web browser instead of the Webview. In that page, if you do something like:

```typescript
    const link = new URLSearchParams(window.location.search).get('link');
    window.location.href = link ? encodeURI(link) : '/';
```

It will take the `link` query param and by setting `window.location.href` on the native browser, allow the native OS to intercept that data link as you originally intended.

I don't know how else to get the Webview to open calendar links natively, but this did the job for what I was trying to accomplish.
